#!/bin/sh
# NOTE: GENERATED BY generate-run-all-llms.sh -- DO NOT MODIFY BY HAND
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/quantized-gemma-2b-it'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/quantized-gemma-2b-it
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/granite-3.3-2b-instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/granite-3.3-2b-instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Mistral-7B-Instruct-v0.3-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Mistral-7B-Instruct-v0.3-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Meta-Llama-3-8B-Instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Meta-Llama-3-8B-Instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-4B-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-4B-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen1.5-0.5B-Chat-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen1.5-0.5B-Chat-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-1.7B-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-1.7B-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Mistral-Nemo-Instruct-2407-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Mistral-Nemo-Instruct-2407-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/gemma-2-9b-it-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/gemma-2-9b-it-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen2.5-7B-Instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen2.5-7B-Instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-0.6B-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-0.6B-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/CodeLlama-13b-Instruct-hf-4bit-MLX'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/CodeLlama-13b-Instruct-hf-4bit-MLX
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-8B-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-8B-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/DeepSeek-R1-Distill-Qwen-7B-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/DeepSeek-R1-Distill-Qwen-7B-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/phi-2-hf-4bit-mlx'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/phi-2-hf-4bit-mlx
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen2.5-1.5B-Instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen2.5-1.5B-Instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/GLM-4-9B-0414-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/GLM-4-9B-0414-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Meta-Llama-3.1-8B-Instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Phi-3.5-mini-instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Phi-3.5-mini-instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Llama-3.2-1B-Instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Llama-3.2-1B-Instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Llama-3.2-3B-Instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Llama-3.2-3B-Instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/OpenELM-270M-Instruct'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/OpenELM-270M-Instruct
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/MiMo-7B-SFT-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/MiMo-7B-SFT-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/SmolLM-135M-Instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/SmolLM-135M-Instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-30B-A3B-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen3-30B-A3B-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/gemma-2-2b-it-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/gemma-2-2b-it-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Phi-3.5-MoE-instruct-4bit'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Phi-3.5-MoE-instruct-4bit
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/SmolVLM-Instruct-4bit --resize 512 --image support/test.jpg'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/SmolVLM-Instruct-4bit --resize 512 --image support/test.jpg
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/paligemma-3b-mix-448-8bit --resize 512 --image support/test.jpg'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/paligemma-3b-mix-448-8bit --resize 512 --image support/test.jpg
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen2.5-VL-3B-Instruct-4bit --resize 512 --image support/test.jpg'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen2.5-VL-3B-Instruct-4bit --resize 512 --image support/test.jpg
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model HuggingFaceTB/SmolVLM2-500M-Video-Instruct-mlx --resize 512 --image support/test.jpg'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model HuggingFaceTB/SmolVLM2-500M-Video-Instruct-mlx --resize 512 --image support/test.jpg
echo
echo ======
echo './mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen2-VL-2B-Instruct-4bit --resize 512 --image support/test.jpg'
./mlx-run llm-tool eval --download ~/Downloads/huggingface --model mlx-community/Qwen2-VL-2B-Instruct-4bit --resize 512 --image support/test.jpg
