version: 2.1

orbs:
  apple: ml-explore/pr-approval@0.1.0

parameters:
  nightly_build:
    type: boolean
    default: false
  weekly_build:
    type: boolean
    default: false

jobs:

  mac_build_and_test:
    parameters:
      xcode_version:
        type: string
    macos:
      xcode: << parameters.xcode_version >>
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Run style checks
          command: |
            pip install pre-commit
            brew install swift-format
            pre-commit run --all
            if ! git diff --quiet; then echo 'Style checks failed, please install pre-commit and run pre-commit run --all and push the change'; exit 1; fi
      - run:
          name: Run Tests (Xcode, macOS)
          command: |
            xcodebuild -version
            xcrun --show-sdk-build-version
            swift --version
            find . -name Package.resolved -exec rm {} \;
            xcodebuild test -scheme mlx-libraries-Package -destination 'platform=OS X'
      - run:
          name: Build Examples
          command: |
            xcodebuild -version
            xcrun --show-sdk-build-version
            swift --version
            find . -name Package.resolved -exec rm {} \;
            xcodebuild -scheme llm-tool
            xcodebuild -scheme image-tool
            xcodebuild -scheme mnist-tool

workflows:
  build_and_test:
    when:
      and:
        - matches:
            pattern: "^(?!pull/)[-\\w]+$"
            value: << pipeline.git.branch >>
        - not: << pipeline.parameters.nightly_build >>
        - not: << pipeline.parameters.weekly_build >>
    jobs:
      - mac_build_and_test:
          matrix:
            parameters:
              xcode_version: ["16.0.0", "16.3.0"]

  prb:
    when:
      matches:
        pattern: "^pull/\\d+(/head)?$"
        value: << pipeline.git.branch >>
    jobs:
      - hold:
          type: approval
      - apple/authenticate:
          context: pr-approval
      - mac_build_and_test:
          requires: [ hold ]
          matrix:
            parameters:
              xcode_version: ["16.0.0", "16.3.0"]
